version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    ports:
      - '3306:3306'
    volumes:
      - /kn_fit/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  
networks:
  default:
    external:
      name: kn-fit-network
