version: '3.8'

services:
  kn_database:
    image: mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: kn_database
    ports:
      - '3306:3306'
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kn_fit_database
      TZ: America/Sao_Paulo
networks:
  default:
    name: kn-fit-network
    external: true
