version: '3.1'

services:
  db:
    image: mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    ports:
      - '3306:3306'
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kn_fit_database
      TZ: America/Sao_Paulo
  
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
  
