#! /bin/bash

# echo
if [ $1 == 'echo' ]; then
    echo 'Fit successful, You can now use fit!'
fi

#docker-up
if [ $1 == 'docker-up' ]; then
    cd ~/.fit
    docker-compose up -d
fi

#docker-down
if [ $1 == 'docker-down' ]; then
    docker rm -f $(docker ps -aq)
fi

#docker-exec
if [ $1 == 'docker-exec' ]; then
    docker exec -it kn_database bash
fi


