CREATE TABLE IF NOT EXISTS `kn_fit_database`.`cref_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` ENUM('CREF9/PR') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;