INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Bíceps', '0');
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Tríceps', '0');
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Glúteos', '0');
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Anteriores', '0');
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Abdômen', '0');
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Trapézio', '0');
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Posteriores', '0');
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Tibial e Fibular', '0');
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Antebraço', '0');
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Lombar', '0');
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Panturrilha', '0');
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Costas', '0');