INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Bíceps', false);
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Tríceps', false);
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Glúteos', false);
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Anteriores', false);
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Abdômen', false);
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Trapézio', false);
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Posteriores', false);
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Tibial e Fibular', false);
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Antebraço', false);
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Lombar', false);
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Panturrilha', false);
INSERT INTO `kn_fit_database`.`muscle_group` (`name`, `blocked`) VALUES ('Costas', false);